version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: po_con
    environment:
      POSTGRES_USER: miki
      POSTGRES_PASSWORD: 1219
      POSTGRES_DB: miki
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  hasura:
    image: hasura/graphql-engine:latest
    container_name: hasura_container
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://miki:1219@po_con:5432/miki
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: miki1219
    ports:
      - "8083:8080"
    restart: always
    networks:
      - app-network

  golang:
    build:
      context: . # Path to your Go application directory
    container_name: go_service
    depends_on:
      - postgres
    environment:
      DB_HOST: po_con
      DB_PORT: 5432
      DB_USER: miki
      DB_PASSWORD: 1219
      DB_NAME: miki
    ports:
      - "8085:8085"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
